#SPDX-License-Identifier: MIT
version: '3'
services:
  augur-db:
    image: postgres:14
    restart: unless-stopped
    environment:
      - "POSTGRES_DB=augur"
      - "POSTGRES_USER=${AUGUR_DB_USER:-augur}"
      - "POSTGRES_PASSWORD=${AUGUR_DB_PASSWORD:-augur}"
    ports:
      - "127.0.0.1:${AUGUR_DB_PORT:-5432}:5432"

  redis:
    image: "redis:alpine"
    ports:
     - 6379:6379

  rabbitmq:
    image: rabbitmq:3
    restart: unless-stopped
    networks:
      - private
    volumes:
      - ./rabbitmq-default.conf:/etc/rabbitmq/rabbitmq.config:ro

  augur:
    image: augur-new:latest
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
      args:
        target: ${AUGUR_STARTUP_TARGET:-default}
    volumes:
      - facade:/augur/facade
    restart: unless-stopped
    networks:
      - private
    ports:
      - 5002:5000
    extra_hosts:
      - "host.docker.internal:host-gateway" #Be able to ping services on the local machine
    environment:
      - "AUGUR_DB=postgresql+psycopg2://${AUGUR_DB_USER:-augur}:${AUGUR_DB_PASSWORD:-augur}@augur-db:5432/augur"
      - "AUGUR_DB_SCHEMA_BUILD=1"
      - "AUGUR_GITHUB_API_KEY=${AUGUR_GITHUB_API_KEY}"
      - "AUGUR_GITLAB_API_KEY=${AUGUR_GITLAB_API_KEY}"
      - "AUGUR_GITHUB_USERNAME=${AUGUR_GITHUB_USERNAME}"
      - "AUGUR_GITLAB_USERNAME=${AUGUR_GITLAB_USERNAME}"
      - REDIS_CONN_STRING=redis://redis:6379
      - RABBITMQ_CONN_STRING=amqp://augur:password123@rabbitmq:5672/augur_vhost
    depends_on:
      - augur-db
      - redis
      - rabbitmq
  
volumes:
  facade:
    driver: local

networks:
  private:
    name: internal
